"""gridpulse_bridge.py — reads GridPulse's (P31) to_joule_format() export
for regional grid-stress context.

Loose coupling by design, not a Python import across repos: GridPulse and
joule are built and versioned as separate repos ("aware of each other,"
per CLAUDE.md's own P20/P31 guidance), so this reads GridPulse's export
JSON file rather than importing GridPulse's code directly. A real sample
(data/gridpulse_export_sample.json) was generated by actually running
`python main.py export --format json` in the gridpulse repo -- not
fabricated to look plausible. `--gridpulse-export PATH` points at a fresh
export from a live GridPulse run.
"""
from __future__ import annotations

import json
import os
from dataclasses import dataclass

DEFAULT_EXPORT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "gridpulse_export_sample.json")


@dataclass
class GridStressContext:
    region: str
    stress_score: float
    tier: str          # LOW / ELEVATED / HIGH / CRITICAL
    renewable_pct: float
    hour: str
    source: str


def load_export(path: str = DEFAULT_EXPORT_PATH) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def get_grid_context(gridpulse_region: str | None, export_path: str = DEFAULT_EXPORT_PATH) -> GridStressContext | None:
    """Returns grid-stress context for an installation's mapped GridPulse
    region, or None if the installation's state isn't one of GridPulse's 6
    covered regions (an honest gap, not silently defaulted to a guess) or
    the export file has no entry for it."""
    if gridpulse_region is None:
        return None
    try:
        export = load_export(export_path)
    except (FileNotFoundError, json.JSONDecodeError):
        return None
    data = export.get(gridpulse_region)
    if data is None:
        return None
    return GridStressContext(
        region=gridpulse_region,
        stress_score=data["stress_score"],
        tier=data["tier"],
        renewable_pct=data["renewable_pct"],
        hour=data["hour"],
        source=f"GridPulse (P31) export, {export_path}",
    )
